-- ⛔ NOT THE SOURCE OF TRUTH ANY MORE. DO NOT EDIT. DO NOT RUN.
--
-- The schema now lives in immutable, timestamp-numbered migrations:
--
--     supabase/migrations/          <- the schema
--     supabase/README.md            <- how to add/apply one
--     docs/Decisions/ADR-011-migrations-are-immutable.md   <- why
--
-- This file's former contents (P0 + P1) are frozen as the squashed baseline:
--     supabase/migrations/20260716120000_baseline_p0_p1.sql
--
-- To set up a database, do NOT paste this into the SQL editor. Run:
--     supabase link --project-ref <ref>
--     supabase db push
-- ...and read supabase/README.md § "Reconciling the live project" FIRST if the
-- project already has tables — the live project's migration ledger and this repo
-- do not yet agree.
--
-- Why this file still exists: `backend/README.md` and several docs pointed here
-- for months, and a deleted file gives a stale link nothing to say. It is a
-- signpost for one release, then it goes ([[ADR-011]]).
--
-- If you are editing this file to change the schema, you want:
--     supabase migration new <what_you_are_doing>
